name: misc_utils
description: Miscellaneous utilities that are useful in different projects
version: 1.0.0

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.4 <4.0.0"

dependencies:
  animations: ^2.0.11
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_file_dialog: ^3.0.2
  freezed_annotation: ^3.1.0
  intl: any
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  transparent_image: ^2.0.1

dev_dependencies:
  build_runner: ^2.8.0
  # custom_lint: any  # Temporarily disabled due to analyzer compatibility
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  lint: ^2.8.0
  # Testing path_provider requires these dependency
  path_provider_platform_interface: ^2.1.2
  # Testing path_provider requires this dependency
  plugin_platform_interface: any

flutter:
  uses-material-design: true
  generate: true
