name: theming
description: A collection of theming related widgets and utilities using riverpod
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.35.4 <4.0.0"

dependencies:
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^3.1.0
  intl: any
  json_annotation: ^4.9.0
  misc_utils:
    path: ../misc_utils
  riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  lint: ^2.8.0
  riverpod_generator: any

flutter:
  uses-material-design: true
  generate: true
